Vagrant::Config.run do |config|
  config.vm.define :lucid32 do |lucid32_config|
    lucid32_config.vm.box = "lucid32"
    lucid32_config.vm.forward_port 80, 4567
    lucid32_config.vm.forward_port 22, 4568
  end

  config.vm.define :db do |db_config|
    db_config.vm.box = "lucid32"
    db_config.vm.forward_port 3306, 3306
  end
end


